spring:
  main:
    web-application-type: NONE
  application:
    name: backend-challenge
binance:
  api:
    base-url: https://api.binance.com/api/v3
    max-memory-size: 16MB
    timeout:
      connection: 30s
      read: 1m
      write: 1m
    order-book:
      depth: 1000
      info-endpoint-timeout: 10s
