name: Run tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Install WG
        run: sudo apt install wireguard

      - name: Setup WG ip
        run: sudo ip link add dev wg0 type wireguard

      - name: Setup WG ip
        run: sudo ip address add dev wg0 10.0.0.5 peer ${{ WG_INTERFACE_ADDRESS }}

      - name: Setup WG ip
        run: |-
          sudo wg set wg0 \
            listen-port ${{ env.WG_INTERFACE_LISTEN_PORT }} \
            private-key privatekey \
            peer ${{ secrets.WG_PEER_PUBLIC_KEY }} \
            allowed-ips 0.0.0.0/0 \
            endpoint ${{ env.WG_PEER_ENDPOINT }}

      - name: Link WG
        run: sudo ip link set up dev wg0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Run tests with Maven
        timeout-minutes: 30
        run: ./mvnw test
